BTE-Trusted-Entity/didsign.io

.github/workflows/pull-request.yaml
package.json
src/Utils/global.d.ts

SK-1236: PR workflow

---

bundlewatch.config.json
package.json
yarn.lock

SK-1434: SDK 0.28.3

---

README.md

SK-1203: update ReadMe

---

src/Components/ImportFiles/ImportFilesVerifier.tsx

SK-1353: remove Redux: fixes

---

src/Components/Privacy/Privacy.tsx

SK-1394: fix links

---

src/components/DidDocument/DidDocument.tsx
src/components/Files/Files.tsx
src/components/JWSErrors/JWSErrors.tsx
src/components/VerifiedFiles/VerifiedFiles.tsx
src/utils/sign-helpers.ts
src/utils/timestamp.ts
src/utils/types.ts
src/utils/verify-helper.ts
src/views/Verify/Verify.tsx

SK-1486: refactor verification flow

---

src/components/DidDocument/DidDocument.tsx

SK-1502: no timestamp message

---

src/utils/verify-helper.ts
src/views/Verify/Verify.tsx

SK-1500: prevent adding to zip

---

package.json
yarn.lock

This reverts commit a3e5e9a428a3f7d866b625938908991da5f47915.

Revert "chore(deps): update parcel to v2.8.0 (#128)"

---

src/views/Verify/Verify.tsx

SK-1500: fix multiple signature files

---

src/components/CredentialsInsertion/CredentialsInsertion.tsx

SK-1536: fix editing credential

---

src/utils/asKiltCoins.ts

SK-1518: more decimal places

---

package.json
yarn.lock

SK-1549: SDK 0.30.0

---

src/components/Credential/Credential.tsx
src/components/ServiceEndpoints/ServiceEndpoint.tsx

SK-1515: Support new credential publishing type

---

src/components/Timestamp/Timestamp.tsx

SK-1665: wrong wallet pops up

---

src/components/Popups/Popups.tsx
src/components/Timestamp/Timestamp.tsx

SK-1668: Fix dropdown

---

src/components/BottomSection/BottomSection.module.css.d.ts
src/components/Popups/Popups.module.css
src/components/Popups/Popups.module.css.d.ts
src/components/Popups/Popups.tsx
src/components/SignButton/SignButton.tsx

SK-1503: Error modals

---

src/components/Credential/Credential.module.css
src/components/Credential/Credential.module.css.d.ts
src/components/Credential/Credential.tsx

SK-1547: link to web3names

---

src/components/BottomSection/InfoLink.tsx

https://github.com/KILTprotocol/ticket/issues/2519

fix external links

---

src/components/Popups/Popups.tsx
src/components/SignButton/SignButton.tsx

https://github.com/KILTprotocol/ticket/issues/2525

fix not authorized

---

src/components/SignButton/SignButton.tsx
src/utils/global.d.ts
src/utils/sign-helpers.ts
src/utils/types.ts

https://github.com/KILTprotocol/ticket/issues/2653

support other wallets

---

.env.example
src/index.tsx
src/utils/checkTestEnvironment.ts

https://github.com/KILTprotocol/ticket/issues/2755

test environment

---

src/components/Credential/Credential.tsx
src/components/DidDocument/DidDocument.tsx

Resolves https://github.com/KILTprotocol/ticket/issues/2939

Link to correct w3n.id environment
